[program:attendance-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/attendance/artisan queue:work --sleep=3 --tries=3
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/attendance-queue.log
stderr_logfile=/var/log/supervisor/attendance-queue-error.log

[group:attendance]
programs=attendance-queue
priority=999
